### ISSUE TITLE
1.7.10 Minecraft Client Crash

### ISSUE THREAD

**Issue by MachinegunMarty** [APengu/LostThaumaturgy#1]
Got a weird problem.

Been playing yesterday (without a problem), and today i can't start my client.
My server works no problems. Even rebooted the server to see if the error would show up there to, but no.

Can't start my client now. It get's to the Main menu and crashes with:

Time: 7-5-17 19:48
Description: Unexpected error

java.lang.NullPointerException: Unexpected error
	at mrdimka.thaumcraft.additions.proxy.KeyBindings.onTick(KeyBindings.java:65)
	at cpw.mods.fml.common.eventhandler.ASMEventHandler_2007_KeyBindings_onTick_ClientTickEvent.invoke(.dynamic)
	at cpw.mods.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:54)
	at cpw.mods.fml.common.eventhandler.EventBus.post(EventBus.java:140)
	at cpw.mods.fml.common.FMLCommonHandler.onPreClientTick(FMLCommonHandler.java:325)
	at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1587)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:973)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:898)
	at net.minecraft.client.main.Main.main(SourceFile:148)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

Happens at every pc that tries to start my pack.

Like i said, been working fine till yesterday.

**Comment by APengu** [comment]
1.7 not supported.

**Comment by MachinegunMarty** [comment]
APengu (MrDimkas).... Really !

Just closed it with not supporting 1.7.10 anymore ????

Maybe you don't understand, but EVERYONE that has your mod can't start his mc client anymore.

Someone on the mc forums also started a thread about it: 
http://www.minecraftforum.net/forums/mapping-and-modding/minecraft-mods/mods-discussion/2819534-thaumicadditions-crash-in-older-world

Problem: I got a world that is unreachable now because of your mod. Technicly not unrechable, because  it's running fine on my server, but my client doesn't start anymore with thaumic additions added.
I even found a fix that i posted for the IC2 bug that was plaging this mod.

Now: I've been hosting a world for 150 days and now my users can't connect and asked me to see if i can get it fixed. So i have been searching this weekend and put this on your Issue tracker so u know this is happening.

Been nothing else of helpfull and respectfull, because i know how much work it is to make a mod, but i atleast expected a normal answer.

Can't you atleast explain the strangeness that is:

I played till 3:30 AM Saterday night (Sunday morning) no problem --> sunday start up client and crash.

Does it have something to do with moving your stuff on github. 
(There is an old post with the same problem apparently, but if i click it the github isn't there anymore) 
Maybe there is a link in the mod checking something that got moved ?

My users want to keep the mod, because they have stuff build out of your mod that they don't want to loose.

Asking as all my users: Could you please shed some light on what might be happening and how we might be able to fix it ?

Thanx in advance

**Comment by APengu** [comment]
OKAY. I will release THE LAST version. Version checker is going to get disabled.

**Comment by MachinegunMarty** [comment]
You are awesome !

Thank you from me and everyone that enjoys your mod so much. 
Will be looking forward to your FINAL release for 1.7.10.

Thanks again for taking the time to make a final version.

Really appreciate your efforts.

**Comment by APengu** [comment]
I don't have much time for 1.7. Crash is fixed; aura - removed.

**Comment by MachinegunMarty** [comment]
I understand man. Really appreciate the time and effort man you put in this mod. 
Would be a shame to see it go to waste. Now people can keep on enjoying your mod.

Again appreciate your time man for the final.

I was the first downloader and ... it works like a charm now.

v0.37

Your awesome man !

**Comment by MachinegunMarty** [comment]
I see you changed it to 0.40. It still downloads 0.37. 
Doesn't matter i will just rename the file to 0.40 then. No sweat.

Thanx again !

**Comment by MachinegunMarty** [comment]
Not me again, but Update:

My server log tells me:  "There are 82 missing blocks and items in this save" they are gonna be removed and the ussual -fml confirm or cancel.

Are they gonna lose there stuff ? or should i run v0.35 on the server, and is this update client only.

(Sorry to have to report to you again on such short notice.)

**Comment by APengu** [comment]
hm... Idk :/

**Comment by MachinegunMarty** [comment]
Will test some more to get more info.

I am starting my server now with 0.35 and got 0.40 on my client. See if i can connect.

If i can, i'm gonna cheat in some stuff from your mod, place it and test then if i update the server.

I will get back to you on this. 

NP happy to help.

**Comment by MachinegunMarty** [comment]
Nope, can't log in with client 0.40 and server 0.35.

No red cross, so i can connect, but half way loading it yells mod rejection 0.35.

So people with SP world would get notice about the missing items to. (I don't know, because i ain't got a SP world, and creating one now would be useless, and impossible with the 0.35 bug, to check)

hmm just gonna update the server. Can always cheat peoples stuff back for them, and got backups, and and.... 

but if you maybe know of fix or something would help allot of people out i think.

**Comment by APengu** [comment]
What items are missing?

**Comment by MachinegunMarty** [comment]
this is the log output:

[20:35:46] [Server thread/ERROR] [FML/]: There are unidentified mappings in this world - we are going to attempt to process anyway
[20:35:46] [Server thread/ERROR] [FML/]: Unidentified block: thaumicadditions:dark_generator, id 3466
[20:35:46] [Server thread/ERROR] [FML/]: Unidentified block: thaumicadditions:symboller, id 3464
[20:35:46] [Server thread/ERROR] [FML/]: Unidentified block: thaumicadditions:thaumic_restorer, id 3469
[20:35:46] [Server thread/ERROR] [FML/]: Unidentified block: thaumicadditions:fluid.pure_warp, id 3484
[20:35:46] [Server thread/ERROR] [FML/]: Unidentified block: thaumicadditions:arc_seal, id 3463
[20:35:46] [Server thread/ERROR] [FML/]: Unidentified block: thaumicadditions:filter, id 3482
[20:35:46] [Server thread/ERROR] [FML/]: Unidentified block: thaumicadditions:hyper_node_creator, id 3470
[20:35:46] [Server thread/ERROR] [FML/]: Unidentified block: thaumicadditions:tile_booster, id 3474
[20:35:46] [Server thread/ERROR] [FML/]: Unidentified block: thaumicadditions:thaumic_generator, id 3468
[20:35:46] [Server thread/ERROR] [FML/]: Unidentified block: thaumicadditions:vis_conduit, id 3480
[20:35:46] [Server thread/ERROR] [FML/]: Unidentified block: thaumicadditions:old_condensator, id 3481
[20:35:46] [Server thread/ERROR] [FML/]: Unidentified block: thaumicadditions:void_chest, id 3477
[20:35:46] [Server thread/ERROR] [FML/]: Unidentified block: thaumicadditions:returner_block, id 3471
[20:35:46] [Server thread/ERROR] [FML/]: Unidentified block: thaumicadditions:eldritch_stone, id 3475
[20:35:46] [Server thread/ERROR] [FML/]: Unidentified block: thaumicadditions:stairs_eldritch, id 3478
[20:35:46] [Server thread/ERROR] [FML/]: Unidentified block: thaumicadditions:infuser, id 3465
[20:35:46] [Server thread/ERROR] [FML/]: Unidentified block: thaumicadditions:tainted_crops, id 3472
[20:35:46] [Server thread/ERROR] [FML/]: Unidentified block: thaumicadditions:tank_basic, id 3462
[20:35:46] [Server thread/ERROR] [FML/]: Unidentified block: thaumicadditions:infuser_activator, id 3473
[20:35:46] [Server thread/ERROR] [FML/]: Unidentified block: thaumicadditions:thaumic_crystallizer, id 3467
[20:35:46] [Server thread/ERROR] [FML/]: Unidentified block: thaumicadditions:tank_reinforced, id 3483
[20:35:47] [Server thread/ERROR] [FML/]: Unidentified block: thaumicadditions:eldritch_lock, id 3476
[20:35:47] [Server thread/ERROR] [FML/]: Unidentified block: thaumicadditions:old_crucible, id 3479
[20:35:47] [Server thread/ERROR] [FML/]: Unidentified item: thaumicadditions:enchanted_silverwood, id 9913
[20:35:47] [Server thread/ERROR] [FML/]: Unidentified item: thaumicadditions:auro_meter, id 9919
[20:35:47] [Server thread/ERROR] [FML/]: Unidentified item: thaumicadditions:thaumic_restorer, id 3469
[20:35:47] [Server thread/ERROR] [FML/]: Unidentified item: thaumicadditions:arcane_dice, id 9915
[20:35:47] [Server thread/ERROR] [FML/]: Unidentified item: thaumicadditions:cap_adaminite_inert, id 9892
[20:35:47] [Server thread/ERROR] [FML/]: Unidentified item: thaumicadditions:adaminite_sword, id 9890
[20:35:47] [Server thread/ERROR] [FML/]: Unidentified item: thaumicadditions:tile_booster, id 3474
[20:35:47] [Server thread/ERROR] [FML/]: Unidentified item: thaumicadditions:pure_warp_bucket, id 9924
[20:35:47] [Server thread/ERROR] [FML/]: Unidentified item: thaumicadditions:arcane_stone, id 9908
[20:35:47] [Server thread/ERROR] [FML/]: Unidentified item: thaumicadditions:filter, id 3482
[20:35:47] [Server thread/ERROR] [FML/]: Unidentified item: thaumicadditions:arc_seal, id 3463
[20:35:47] [Server thread/ERROR] [FML/]: Unidentified item: thaumicadditions:old_crucible, id 3479
[20:35:47] [Server thread/ERROR] [FML/]: Unidentified item: thaumicadditions:singcore, id 9899
[20:35:47] [Server thread/ERROR] [FML/]: Unidentified item: thaumicadditions:tank_reinforced, id 3483
[20:35:47] [Server thread/ERROR] [FML/]: Unidentified item: thaumicadditions:mask_of_cruelty, id 9905
[20:35:47] [Server thread/ERROR] [FML/]: Unidentified item: thaumicadditions:eldritch_lock, id 3476
[20:35:47] [Server thread/ERROR] [FML/]: Unidentified item: thaumicadditions:vis_conduit, id 3480
[20:35:47] [Server thread/ERROR] [FML/]: Unidentified item: thaumicadditions:hyper_node_creator, id 3470
[20:35:47] [Server thread/ERROR] [FML/]: Unidentified item: thaumicadditions:infuser_activator, id 3473
[20:35:47] [Server thread/ERROR] [FML/]: Unidentified item: thaumicadditions:foci_xp, id 9918
[20:35:47] [Server thread/ERROR] [FML/]: Unidentified item: thaumicadditions:depleted_shard, id 9900
[20:35:47] [Server thread/ERROR] [FML/]: Unidentified item: thaumicadditions:adaminite_helmet, id 9920
[20:35:47] [Server thread/ERROR] [FML/]: Unidentified item: thaumicadditions:infuser, id 3465
[20:35:47] [Server thread/ERROR] [FML/]: Unidentified item: thaumicadditions:adaminite_leggings, id 9922
[20:35:47] [Server thread/ERROR] [FML/]: Unidentified item: thaumicadditions:adaminite_chestplate, id 9921
[20:35:47] [Server thread/ERROR] [FML/]: Unidentified item: thaumicadditions:eldritch_stone, id 3475
[20:35:47] [Server thread/ERROR] [FML/]: Unidentified item: thaumicadditions:seal_symbol, id 9898
[20:35:47] [Server thread/ERROR] [FML/]: Unidentified item: thaumicadditions:adaminite_boots, id 9923
[20:35:47] [Server thread/ERROR] [FML/]: Unidentified item: thaumicadditions:dark_generator, id 3466
[20:35:47] [Server thread/ERROR] [FML/]: Unidentified item: thaumicadditions:wand_hallelujah, id 9914
[20:35:47] [Server thread/ERROR] [FML/]: Unidentified item: thaumicadditions:wand_staff_adaminitewood, id 9909
[20:35:47] [Server thread/ERROR] [FML/]: Unidentified item: thaumicadditions:mithrillium_ingot, id 9895
[20:35:47] [Server thread/ERROR] [FML/]: Unidentified item: thaumicadditions:cap_mithrillium_inert, id 9896
[20:35:47] [Server thread/ERROR] [FML/]: Unidentified item: thaumicadditions:infusion_book, id 9903
[20:35:47] [Server thread/ERROR] [FML/]: Unidentified item: thaumicadditions:fluid.pure_warp, id 3484
[20:35:47] [Server thread/ERROR] [FML/]: Unidentified item: thaumicadditions:singularity, id 9894
[20:35:47] [Server thread/ERROR] [FML/]: Unidentified item: thaumicadditions:cap_mithrillium, id 9897
[20:35:47] [Server thread/ERROR] [FML/]: Unidentified item: thaumicadditions:foci_projectile, id 9917
[20:35:47] [Server thread/ERROR] [FML/]: Unidentified item: thaumicadditions:tainted_crops, id 3472
[20:35:47] [Server thread/ERROR] [FML/]: Unidentified item: thaumicadditions:tainted_roots, id 9907
[20:35:47] [Server thread/ERROR] [FML/]: Unidentified item: thaumicadditions:void_chest, id 3477
[20:35:47] [Server thread/ERROR] [FML/]: Unidentified item: thaumicadditions:tainted_seed, id 9906
[20:35:47] [Server thread/ERROR] [FML/]: Unidentified item: thaumicadditions:thaumic_crystallizer, id 3467
[20:35:47] [Server thread/ERROR] [FML/]: Unidentified item: thaumicadditions:old_condensator, id 3481
[20:35:47] [Server thread/ERROR] [FML/]: Unidentified item: thaumicadditions:transporter.arcane, id 9916
[20:35:47] [Server thread/ERROR] [FML/]: Unidentified item: thaumicadditions:symboller, id 3464
[20:35:47] [Server thread/ERROR] [FML/]: Unidentified item: thaumicadditions:tank_basic, id 3462
[20:35:47] [Server thread/ERROR] [FML/]: Unidentified item: thaumicadditions:soul_fragment, id 9902
[20:35:47] [Server thread/ERROR] [FML/]: Unidentified item: thaumicadditions:wand_rod_adaminitewood, id 9893
[20:35:47] [Server thread/ERROR] [FML/]: Unidentified item: thaumicadditions:cap_adaminite, id 9891
[20:35:47] [Server thread/ERROR] [FML/]: Unidentified item: thaumicadditions:adaminite_ingot, id 9889
[20:35:47] [Server thread/ERROR] [FML/]: Unidentified item: thaumicadditions:keystone, id 9904
[20:35:47] [Server thread/ERROR] [FML/]: Unidentified item: thaumicadditions:enchanted_greatwood, id 9912
[20:35:47] [Server thread/ERROR] [FML/]: Unidentified item: thaumicadditions:old_upgrade, id 9911
[20:35:47] [Server thread/ERROR] [FML/]: Unidentified item: thaumicadditions:seal_globe, id 9901
[20:35:47] [Server thread/ERROR] [FML/]: Unidentified item: thaumicadditions:returner_block, id 3471
[20:35:47] [Server thread/ERROR] [FML/]: Unidentified item: thaumicadditions:seal_item, id 9910
[20:35:47] [Server thread/ERROR] [FML/]: Unidentified item: thaumicadditions:thaumic_generator, id 3468
[20:35:47] [Server thread/ERROR] [FML/]: Unidentified item: thaumicadditions:stairs_eldritch, id 3478
[20:35:48] [Server thread/WARN] [FML/]: Forge Mod Loader detected missing blocks/items.

There are 82 missing blocks and items in this save.
If you continue the missing blocks/items will get removed.
A world backup will be automatically created in your saves directory.

Missing Blocks/Items:
thaumicadditions:dark_generator
thaumicadditions:symboller
thaumicadditions:thaumic_restorer
thaumicadditions:fluid.pure_warp
thaumicadditions:arc_seal
thaumicadditions:filter
thaumicadditions:hyper_node_creator
thaumicadditions:tile_booster
thaumicadditions:thaumic_generator
thaumicadditions:vis_conduit
thaumicadditions:old_condensator
thaumicadditions:void_chest
thaumicadditions:returner_block
thaumicadditions:eldritch_stone
thaumicadditions:stairs_eldritch
thaumicadditions:infuser
thaumicadditions:tainted_crops
thaumicadditions:tank_basic
thaumicadditions:infuser_activator
thaumicadditions:thaumic_crystallizer
thaumicadditions:tank_reinforced
thaumicadditions:eldritch_lock
thaumicadditions:old_crucible
thaumicadditions:enchanted_silverwood
thaumicadditions:auro_meter
thaumicadditions:thaumic_restorer
thaumicadditions:arcane_dice
thaumicadditions:cap_adaminite_inert
thaumicadditions:adaminite_sword
thaumicadditions:tile_booster
thaumicadditions:pure_warp_bucket
thaumicadditions:arcane_stone
thaumicadditions:filter
thaumicadditions:arc_seal
thaumicadditions:old_crucible
thaumicadditions:singcore
thaumicadditions:tank_reinforced
thaumicadditions:mask_of_cruelty
thaumicadditions:eldritch_lock
thaumicadditions:vis_conduit
thaumicadditions:hyper_node_creator
thaumicadditions:infuser_activator
thaumicadditions:foci_xp
thaumicadditions:depleted_shard
thaumicadditions:adaminite_helmet
thaumicadditions:infuser
thaumicadditions:adaminite_leggings
thaumicadditions:adaminite_chestplate
thaumicadditions:eldritch_stone
thaumicadditions:seal_symbol
thaumicadditions:adaminite_boots
thaumicadditions:dark_generator
thaumicadditions:wand_hallelujah
thaumicadditions:wand_staff_adaminitewood
thaumicadditions:mithrillium_ingot
thaumicadditions:cap_mithrillium_inert
thaumicadditions:infusion_book
thaumicadditions:fluid.pure_warp
thaumicadditions:singularity
thaumicadditions:cap_mithrillium
thaumicadditions:foci_projectile
thaumicadditions:tainted_crops
thaumicadditions:tainted_roots
thaumicadditions:void_chest
thaumicadditions:tainted_seed
thaumicadditions:thaumic_crystallizer
thaumicadditions:old_condensator
thaumicadditions:transporter.arcane
thaumicadditions:symboller
thaumicadditions:tank_basic
thaumicadditions:soul_fragment
thaumicadditions:wand_rod_adaminitewood
thaumicadditions:cap_adaminite
thaumicadditions:adaminite_ingot
thaumicadditions:keystone
thaumicadditions:enchanted_greatwood
thaumicadditions:old_upgrade
thaumicadditions:seal_globe
thaumicadditions:returner_block
thaumicadditions:seal_item
thaumicadditions:thaumic_generator
thaumicadditions:stairs_eldritch


Run the command /fml confirm or or /fml cancel to proceed.
Alternatively start the server with -Dfml.queryResult=confirm or -Dfml.queryResult=cancel to preselect the answer.

I just /fml confirm it.

This is what i get on the server. SP people should get it to loading an existing world.

But to test: i got no adaminite or staff on me or anything from your mod to see if i lost it or not, haven't done any research in the thauminomicon on your tab yet.
So that's not a big help here now.
Once's my server is finally done loading the world, i will test if it is atleast findable through NEI and if the thauminomicon tab is there.

That's all i can do for now. Will report back.

**Comment by APengu** [comment]
Impossible... I loaded my old year and it missed only aura meter... :/

**Comment by MachinegunMarty** [comment]
Wish i had better news man....

Can't find anything anymore from the mod now, not in NEI.
Thauminomicom had no Thaumic Additions Tab, it just disappeared....

So while i'm typing, i'm making a new SP world on my desktop to test.

Same result mate, can't find anything anymore. Search with @, searched for adaminite.. nothing shows up ?

Just reporting what is see.

(In case your wondering: i've been a System and Network Administrator for the last 15 years, so i know my shit around, just don't know coding. That's a seperate sport i always say :-)
So when i say on my server, i mean: 2xQuad Core CPU's with Hyper Threading(16 cpu tot.) and 144 Gb of mem.
But 264 Mods take there time to load up a world, so that slows me down testing.

So i'm trying to help as best i can, and try to report as best i can for you.

**Comment by APengu** [comment]
Please verify that TA is installed

**Comment by MachinegunMarty** [comment]
Double checked and redownloading now just to be sure.
Not gonna rename to 0.40, and will not remove 1.7.10 infront of the mod name this time, and test a SP world.

**Comment by MachinegunMarty** [comment]
1. Downloaded fresh copy
2. removed the old mod
3. Placed the fresh copy in mods folder
4. Load MC Forge 1.7.10-1614

Made a new Creative SP world, swapped /gamemode 0  and searched NEI but can't find anything anymore of your mod.
I just don't understand.
I can't delete the .jar from the mod folder now because it is in use, so it is loaded up but ???

**Comment by APengu** [comment]
Now I have no idea why that happens :/

**Comment by MachinegunMarty** [comment]
You got me to man.

If someone else could try and verify that it's working or not, that would be appreciated.

Server: I loaded a backup. Tried and got the missing blocks message again. Confirm and can't find anything.
Client: I load up a old world or new and can't find anything anymore of your mod.

So that's 3 seperate worlds that are all missing your items now.

How a final fix turns in a final nightmare for you.  I feel for you man.

I will test some more tommorrow on seperate pc's to see what that gives.

Thanks for your patience and time !

**Comment by MachinegunMarty** [comment]
Good morning mate.

Testing @ work on my laptop. New world, cannot find anything from the mod in the NEI and no tab in Thauminomicom.

Been looking trough posts and such to see if people tested or something.

And they did:  http://www.minecraftforum.net/forums/mapping-and-modding/minecraft-mods/mods-discussion/2819534-thaumicadditions-crash-in-older-world

He has the same problem. No tab in the thauminomicon.

Will look if i can find anything or do something for you to help out.

**Comment by APengu** [comment]
Morning, can we discuss this on twitch app/discord? this is faster :)

**Comment by MachinegunMarty** [comment]
If i wasn't at work i would/ could gladly.
Can start discord up tho, so i atleast have your channel and we can type.
Can join in this afternoon/ tonight in voice in discord. 

Just send me a pm.

**Comment by APengu** [comment]
But i need your id you find you

**Comment by MachinegunMarty** [comment]
Machinegun Marty#9498
