### ISSUE TITLE
Odd crash after two weeks of playing

### ISSUE THREAD

**Issue by 08heat28md** [APengu/LostThaumaturgy#2]
My game crashes consistently upon finishing its launch to the title screen, a few seconds later closing and giving me an error.  I have discovered this crash is caused by your mod Thaumic Additions and it is a problem that has only started happening today in the last hour.  I have used your mod on my server world for around two weeks now will no problems, but only starting today experienced this issue.  I already have numerous high tier items such as the wand storing 2000 vis and its staff counterpart.  Because of this, I'd very much prefer if I did not have to get rid of this mod as I have been having a positive experience with it for the past couple of days.

I am using Minecraft 1.7.10 with Thaumcraft on a server that has had the mod for two weeks now with no problems.  Getting rid of the mod works but I would prefer if did not have to delete it.  I tried fixing the error by using only the mods and versions folder upon launch and also by renaming the file.  I do not have IC2 installed.

Crash report #1 had the same issue, and that user was also on version 1.7.10, supported by your mod as it says in its title.

Here is the crash report: 

Unexpected error

java.lang.NullPointerException: Unexpected error
	at mrdimka.thaumcraft.additions.proxy.KeyBindings.onTick(KeyBindings.java:65)
	at cpw.mods.fml.common.eventhandler.ASMEventHandler_704_KeyBindings_onTick_ClientTickEvent.invoke(.dynamic)
	at cpw.mods.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:54)
	at cpw.mods.fml.common.eventhandler.EventBus.post(EventBus.java:140)
	at cpw.mods.fml.common.FMLCommonHandler.onPreClientTick(FMLCommonHandler.java:325)
	at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1587)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:973)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:898)
	at net.minecraft.client.main.Main.main(SourceFile:148)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

Hopefully, you can help.  Thank you!

**Comment by APengu** [comment]
1.7 not supported!

**Comment by 08heat28md** [comment]
If 1.7 is not supported then why do you have numerous downloads for that version? This mod worked for a whole two weeks before and then suddenly stopped working. Do you not have any explanation for this?

**Comment by APengu** [comment]
Yes, I do. I removed repository for Thaumic Additions

**Comment by 08heat28md** [comment]
Why would you do that? Did you end support for the mod altogether or just for 1.7? I have a feeling that a lot of people still play modded 1.7 so I see no reason why you did that except to get space for other things. I still don't see why that would prevent me from launching Minecraft altogether, though.

**Comment by APengu** [comment]
version checker bug. I removed it in a final version. And you can say that i ended support for "Thaumic Additions" altogether, but I'm working on "Lost Thaumaturgy" now.

**Comment by 08heat28md** [comment]
I see. Sorry for the confusion.
